baseURL = "https://kaderovski.com"
languageCode = "en-us"
title = "Kaderovski"
theme="archie"
copyright = "© Kaderovski"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Some tech & personal posts." 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/corentinderet"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/f00b4rch"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[menu.main]]
name = "Photos"
url = "https://photos.kaderovski.com"
weight = 5

[[menu.main]]
name = "CV"
url = "/cv"
weight = 6
